name: Release Oolite

on:
  release:
    types: [created]   # Trigger only when a new release is created
permissions:
  contents: write
jobs:
  run:
    runs-on: windows-2025

    steps:
    - uses: actions/checkout@v5
    - name: Set up MSYS2 (MinGW)
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
    - name: Download latest release assets
      uses: robinraju/release-downloader@v1
      with:
        repository: mcarans/oolite_mingw64_environment
        latest: true
        fileName: "*"
        out-file-path: ./packages
    - name: Install
      shell: msys2 {0}
      run: |
        ./install.sh -deployment

    # Upload artifacts to the release
    - name: Upload to GitHub Release
      if: success()
      uses: softprops/action-gh-release@v2
      with:
        files: installer/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Delete release and tag on failure
      if: failure()
      run: |
        # Install GitHub CLI
        choco install gh -y

        # Authenticate GitHub CLI
        gh auth login --with-token < $env:GITHUB_TOKEN

        # Delete the release and tag
        gh release delete $env:GITHUB_REF_NAME --cleanup-tag --yes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REF_NAME: ${{ github.event.release.tag_name }}
